import jsPDF from "jspdf";
import type { CVReport } from "./analyze";

// Generates an ATS-friendly PDF (plain text, single column, standard fonts)
// containing the optimized skills section and recommended keywords.
export function exportAtsPdf(report: CVReport) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 54;
  const maxW = pageW - margin * 2;
  let y = margin;

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin) {
      doc.addPage();
      y = margin;
    }
  };

  const writeHeading = (text: string, size = 16) => {
    ensureSpace(size + 14);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(size);
    doc.text(text, margin, y);
    y += size + 8;
  };

  const writeSubheading = (text: string) => {
    ensureSpace(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(text.toUpperCase(), margin, y);
    y += 14;
  };

  const writeBody = (text: string, size = 11) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(size);
    const lines = doc.splitTextToSize(text, maxW);
    for (const line of lines) {
      ensureSpace(size + 4);
      doc.text(line, margin, y);
      y += size + 4;
    }
  };

  const writeSkillRow = (label: string, items: string[]) => {
    if (!items.length) return;
    writeSubheading(label);
    writeBody(items.join(" • "));
    y += 6;
  };

  // Header
  writeHeading(report.candidate || "Your CV", 18);
  if (report.targetRole) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(90);
    doc.text(`Target role: ${report.targetRole}`, margin, y);
    doc.setTextColor(0);
    y += 16;
  }
  doc.setDrawColor(200);
  doc.line(margin, y, pageW - margin, y);
  y += 18;

  // Skills section
  writeHeading("Optimized Skills Section", 14);
  writeSkillRow("Core Competencies", report.skillsSection.coreCompetencies);
  writeSkillRow("Technical", report.skillsSection.technical);
  writeSkillRow("Tools & Platforms", report.skillsSection.tools);
  writeSkillRow("Soft Skills", report.skillsSection.soft);

  y += 8;

  // ATS Keywords
  writeHeading("ATS Keyword Recommendations", 14);
  writeBody(`Match score: ${report.atsKeywords.matchScore}%`);
  y += 4;

  if (report.atsKeywords.recommended.length) {
    writeSubheading("Priority keywords to add");
    writeBody(report.atsKeywords.recommended.join(", "));
    y += 4;
  }
  if (report.atsKeywords.present.length) {
    writeSubheading("Keywords already present");
    writeBody(report.atsKeywords.present.join(", "));
    y += 4;
  }
  if (report.atsKeywords.missing.length) {
    writeSubheading("Missing keywords to consider");
    writeBody(report.atsKeywords.missing.join(", "));
  }

  // Footer note
  ensureSpace(30);
  y = Math.max(y + 16, pageH - margin - 14);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text("Generated by RoastMyCV AI — ATS-ready export", margin, y);
  doc.setTextColor(0);

  const safeName = (report.candidate || "cv").replace(/[^a-z0-9]+/gi, "_").toLowerCase();
  doc.save(`${safeName}_ats_skills.pdf`);
}
